### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions

### ISSUE THREAD

**Issue by FJBDev** [RomanIakovlev/timeshape#25]
Here is the issue I am getting when I upgraded from 2018d.4 to 2018d.6 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions
	at org.apache.commons.compress.archivers.sevenz.Coders.<clinit>(Coders.java:47)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecoderStack(SevenZFile.java:1032)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecodingStream(SevenZFile.java:985)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.getNextEntry(SevenZFile.java:297)
	at net.iakovlev.timeshape.TimeZoneEngine.lambda$initialize$0(TimeZoneEngine.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.iakovlev.timeshape.Index.build(Index.java:68)
	at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:88)
	at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:59)

**Comment by RomanIakovlev** [comment]
I'd suggest to do a clean and rebuild. Timeshape version 2018d.6 doesn't use that dependency (org/tukaani/xz/) anymore, but the older versions did use it, so it looks like some class files in your program were not properly updated. 
If this suggestion doesn't help, it would be useful to get a minimal example that reproduces this issue reliably.

**Comment by FJBDev** [comment]
My bad, a "Maven clean" seems to have resolved my issue. I'm closing it.
